version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: glorified-todo-postgres-user-db
    environment:
      POSTGRES_DB: glorified_todo_user_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - user_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d glorified_todo_user_db"]
      interval: 5s
      timeout: 3s
      retries: 20

volumes:
  user_db_data:
