spring:
  application:
    name: to-do-app

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5433/glorified_todo_todo_db}
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yml

server:
  port: 8081

logging:
  level:
    root: INFO
    liquibase: DEBUG
    liquibase.changelog: DEBUG
    liquibase.executor: DEBUG
    liquibase.database: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE